// Tokens to code (plan 0022 §K, decision D10): the one design tokens file the Penpot library is
// built from becomes the CSS custom properties every screen is styled with, so the app and the
// designs cannot drift apart.
//
//   node tools/tokens/build.mjs [--tokens <file.tokens.json>] [--out <file.css>]
//
// Defaults: docs/ux/tokens/innytypes.tokens.json in, app/dist/generated/tokens.css out. The
// output is build output and is never committed.
//
// The tokens file is DTCG with three sets: `base` (raw values), `light` and `dark` (semantic
// aliases of base values). Every token becomes `--inny-<path>`, the set name left out:
//
//   base.color.paper.1      -> --inny-color-paper-1: #f5f6f3;
//   light.surface.canvas    -> --inny-surface-canvas: var(--inny-color-paper-1);
//
// `base` and `light` are the `:root` defaults. `dark` applies twice: under
// `prefers-color-scheme: dark` unless the page pins `data-theme="light"`, and whenever the page
// pins `data-theme="dark"`. Output order follows the file, so the same file always builds the
// same bytes.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const DEFAULT_TOKENS = path.join(REPO, "docs", "ux", "tokens", "innytypes.tokens.json");
const DEFAULT_OUT = path.join(REPO, "app", "dist", "generated", "tokens.css");

const PREFIX = "--inny-";
const HEADER =
  "/* Generated by tools/tokens/build.mjs from the design tokens file. Do not edit. */";

/** A token is an object carrying `$value`; anything else that is an object is a group. */
function isToken(node) {
  return node !== null && typeof node === "object" && "$value" in node;
}

/**
 * Every token of one set, in file order, as [path segments, token]. Keys starting with `$`
 * ($type, $description) are metadata, not groups.
 */
function flatten(group, trail = []) {
  const tokens = [];
  for (const [key, node] of Object.entries(group)) {
    if (key.startsWith("$")) {
      continue;
    }
    const segments = [...trail, key];
    if (isToken(node)) {
      tokens.push([segments, node]);
      continue;
    }
    if (node === null || typeof node !== "object") {
      throw new Error(`tokens: ${segments.join(".")} is neither a token nor a group`);
    }
    tokens.push(...flatten(node, segments));
  }
  return tokens;
}

/** The custom property name of a token path inside its set. */
function propertyName(segments) {
  return PREFIX + segments.join("-");
}

/** A font family list: names with spaces are quoted, generic families are not. */
function fontFamily(value) {
  const families = Array.isArray(value) ? value : [value];
  return families.map((family) => (/\s/.test(family) ? `"${family}"` : family)).join(", ");
}

/** One DTCG shadow (or a list of them) as a CSS box-shadow value. */
function shadow(value, resolve) {
  const layers = Array.isArray(value) ? value : [value];
  return layers
    .map((layer) =>
      [layer.offsetX, layer.offsetY, layer.blur, layer.spread, resolve(layer.color)].join(" "),
    )
    .join(", ");
}

/**
 * A token's CSS value. An alias (`{base.color.paper.1}`) becomes a var() of the aliased
 * token, which must exist; anything unknown is refused rather than guessed at.
 */
function cssValue(set, segments, token, known) {
  const where = [set, ...segments].join(".");
  const resolve = (value) => {
    if (typeof value !== "string") {
      return String(value);
    }
    const alias = /^\{([^}]+)\}$/.exec(value);
    if (alias === null) {
      return value;
    }
    // The first segment of an alias names its set; the property name leaves the set out.
    const target = alias[1].split(".").slice(1);
    const name = propertyName(target);
    if (!known.has(name)) {
      throw new Error(`tokens: ${where} refers to ${alias[1]}, which is not a token`);
    }
    return `var(${name})`;
  };

  switch (token.$type) {
    case "color":
    case "dimension":
    case "duration":
    case "fontWeight":
    case "number":
    case "opacity":
      return resolve(token.$value);
    case "fontFamily":
      return fontFamily(token.$value);
    case "shadow":
      return shadow(token.$value, resolve);
    default:
      throw new Error(`tokens: ${where} has a $type this build does not know: ${token.$type}`);
  }
}

/** The declarations of one set, one per line, indented by `indent`. */
function declarations(set, tokens, known, indent) {
  return tokens
    .map(([segments, token]) => {
      return `${indent}${propertyName(segments)}: ${cssValue(set, segments, token, known)};`;
    })
    .join("\n");
}

/** The CSS for a parsed tokens document. Throws on anything it cannot translate faithfully. */
export function buildTokensCss(document) {
  for (const set of ["base", "light", "dark"]) {
    if (document[set] === null || typeof document[set] !== "object") {
      throw new Error(`tokens: the file has no "${set}" set`);
    }
  }
  const base = flatten(document.base);
  const light = flatten(document.light);
  const dark = flatten(document.dark);

  // Both themes are complete (docs/ux/design-system.md, "Dark mode"): every semantic token
  // has a value in each, so a theme can never fall back to the other's colour.
  const lightNames = light.map(([segments]) => propertyName(segments));
  const darkNames = dark.map(([segments]) => propertyName(segments));
  const onlyLight = lightNames.filter((name) => !darkNames.includes(name));
  const onlyDark = darkNames.filter((name) => !lightNames.includes(name));
  if (onlyLight.length > 0 || onlyDark.length > 0) {
    throw new Error(
      `tokens: the light and dark sets differ: only light ${JSON.stringify(onlyLight)}, ` +
        `only dark ${JSON.stringify(onlyDark)}`,
    );
  }

  // A semantic name that is also a base name would make one of them silently win.
  const baseNames = new Set(base.map(([segments]) => propertyName(segments)));
  const clash = lightNames.filter((name) => baseNames.has(name));
  if (clash.length > 0) {
    throw new Error(`tokens: semantic tokens shadow base tokens: ${JSON.stringify(clash)}`);
  }
  const known = new Set([...baseNames, ...lightNames]);

  return [
    HEADER,
    "",
    ":root {",
    declarations("base", base, known, "  "),
    declarations("light", light, known, "  "),
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    declarations("dark", dark, known, "    "),
    "  }",
    "}",
    "",
    ':root[data-theme="dark"] {',
    declarations("dark", dark, known, "  "),
    "}",
    "",
  ].join("\n");
}

/** The value following `flag` on the command line, or the fallback. */
function option(args, flag, fallback) {
  const at = args.indexOf(flag);
  if (at === -1) {
    return fallback;
  }
  const value = args[at + 1];
  if (value === undefined) {
    throw new Error(`tokens: ${flag} needs a value`);
  }
  return path.resolve(value);
}

function main(args) {
  const tokensFile = option(args, "--tokens", DEFAULT_TOKENS);
  const outFile = option(args, "--out", DEFAULT_OUT);
  const css = buildTokensCss(JSON.parse(fs.readFileSync(tokensFile, "utf8")));
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, css);
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    main(process.argv.slice(2));
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
